[package]
name = "microservice"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
csv = "1.3"
tower-http = { version = "0.6.6", features = ["cors"] }
