services:
  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "5173:5173" 
    depends_on:
      - backend
      - rust-service
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_RUST_API_URL=http://rust-service:8080
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  rust-service:
    build: ./microservice
    container_name: rust_axum_service
    ports:
      - "8080:8080"
    networks:
      - app-network

  # localstack:
  #   container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
  #   image: localstack/localstack
  #   ports:
  #     - "127.0.0.1:4566:4566"            # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  #   environment:
  #     - DEBUG=${DEBUG:-0}
  #   volumes:
  #     - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  app-network:
    driver: bridge
