name: CI/CD Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ==========================
      # FRONTEND
      # ==========================
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # ==========================
      # BACKEND
      # ==========================
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      # ==========================
      # DEPLOYMENT
      # ==========================
      - name: Deploy Vercel Frontend
        env:
          deploy_url: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

      - name: Deploy Render Backend
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

        
      - name: Deploy Render Microservice
        env:
          deploy_url: ${{ secrets.RENDER_MICROSERVICE_DEPLOY_HOOK_URL }}  
        run: |
          curl "$deploy_url"
